### ISSUE TITLE
Double quotes don't work with gsutil

### ISSUE THREAD

**Issue by borekb** [mbuilov/gnumake-windows#1]
Hi, I'm hitting a very strange issue, not sure what is causing it but something between `make.exe` and shell (Git Bash in my case) might be the issue. It happens with the [`gsutil`](https://cloud.google.com/storage/docs/gsutil) utility from Google Cloud SDK.

First, plain command line (Git Bash):

```
$ which gsutil
which: no gsutil in ... (path)

$ where gsutil
C:\Users\borek\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gsutil.cmd
```

Test `Makefile`:

```
test1:
	gsutil --version

test2:
	gsutil cat "gs://vp-builds/vpcom-plugin/prod_deployment_version.txt"

test3:
	gsutil cat gs://vp-builds/vpcom-plugin/prod_deployment_version.txt

test4:
	gsutil cat 'gs://vp-builds/vpcom-plugin/prod_deployment_version.txt'
```

And running the targets:

```
$ make test1
gsutil --version
gsutil version: 4.31

$ make test2
gsutil cat "gs://vp-builds/test/prod_deployment_version.txt"
/usr/bin/sh: gsutil: command not found
make: *** [Makefile:7: test2] Error 127

$ make test3
gsutil cat gs://vp-builds/test/prod_deployment_version.txt
8f588f6

$ make test4
gsutil cat 'gs://vp-builds/test/prod_deployment_version.txt'
8f588f6
```

As you can see, the syntax with doublequotes doesn't work via make (I'm using [`gnumake-4.2.1-x64.exe`](https://github.com/mbuilov/gnumake-windows/blob/master/gnumake-4.2.1-x64.exe) on Windows 10). It works fine when pasted to the console:

```
$ gsutil cat "gs://vp-builds/vpcom-plugin/prod_deployment_version.txt"
8f588f6
```

Because of this difference between plain CLI and executing it via `make`, it makes me think that the issue might be make-related but I'm not at all sure.

**Comment by mbuilov** [comment]
Hello.

Well, in simple cases, as optimization, gnu make may avoid creating a shell
sub-process in target rules and just call commands directly.

Normally, for complex commands, or if shell is not known to gnu make, it
executes commands like: *shell -c "command"*.

For the cases without double quotes (*test1*, *test3 *and *test4*) -
optimization works, gnu make just executes the commands directly (in the
current directory).

But for *test2*, gnu make starts something like:

/usr/bin/sh.exe -c "gsutil cat
\"gs://vp-builds/vpcom-plugin/prod_deployment_version.txt\""

And, because gsutil is not in the paths searched by /usr/bin/sh.exe, this
command fails.


PS.
You may look at gnu make sources - function
*construct_command_argv_internal()* (in job.c)
Where the code jumps to the "*slow*:" label - make cannot optimize and uses
shell.


Cheers,
Michael

**Comment by borekb** [comment]
Thanks, that was very useful. I realized `gsutil` for Windows ships only with `gsutil.cmd` and no plain `gsutil`, and while I had `alias gsutil='gsutil.cmd'` in my `.bashrc`, this was not loaded internally by `make` so I was getting `/usr/bin/sh: gsutil: command not found`.

I fixed it by creating a small "proxy" `gsutil` file in my PATH:

```
#!/bin/bash

"gsutil.cmd" "$@"
```

which makes everything work as expected. Thanks!
